# Generated by Django 4.1.2 on 2022-12-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_note', '0002_alter_note_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='account',
            new_name='teacher',
        ),
    ]
