# Generated by Django 4.1.2 on 2022-10-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_status_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_day',
            field=models.IntegerField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')]),
        ),
    ]
