# Generated by Django 4.1.2 on 2022-10-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_lesson_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=50),
        ),
    ]
