# Generated by Django 4.1.2 on 2022-10-23 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0005_alter_lesson_lesson_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('lesson_time', 'lesson_day', 'teacher', 'name')},
        ),
    ]
