# Generated by Django 4.1.2 on 2022-12-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='class_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
